-- Script para insertar un documento de prueba con archivo
INSERT INTO documentos (
  titulo, 
  descripcion, 
  contenido, 
  tipo, 
  categoria_id, 
  autor_id, 
  tags, 
  nivel_acceso, 
  keywords, 
  estado,
  archivo_url,
  archivo_nombre_original,
  archivo_extension,
  archivo_size,
  archivo_tipo_mime,
  vistas
) VALUES (
  'Documento de Prueba con Archivo',
  'Este es un documento de prueba para verificar que el sistema de descarga funciona correctamente.',
  '<h2>Contenido del Documento</h2><p>Este documento incluye un archivo de prueba que se puede descargar para verificar el funcionamiento del sistema.</p>',
  'documento',
  1,
  1,
  'prueba,test,archivo,descarga',
  'publico',
  'prueba test archivo descarga funcionalidad',
  'activo',
  '/uploads/documento_prueba.txt',
  'documento_prueba.txt',
  '.txt',
  512,
  'text/plain',
  0
);